#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "$0")/.." && pwd)"
question="对比 GraphRAG 和 Execution-first 的差异"

modes=(reference digest transform evolve)

for mode in "${modes[@]}"; do
  settings="$repo_dir/settings/${mode}.yaml"
  out_file="$repo_dir/examples/demo_${mode}.md"
  cmd=(python3 "$repo_dir/scripts/run.py" --intent compare_frameworks --question "$question" --settings "$settings")
  output="$("${cmd[@]}")"
  {
    echo "# Demo Output (${mode})"
    echo
    echo "Generated by:"
    echo
    echo "\`\`\`bash"
    echo "${cmd[@]#python3 }"
    echo "\`\`\`"
    echo
    echo "---"
    echo
    echo "$output"
  } > "$out_file"
  echo "Wrote $out_file"
 done

cat > "$repo_dir/examples/demo.md" <<'MD'
# Demo Outputs

- [Reference](demo_reference.md)
- [Digest](demo_digest.md)
- [Transform](demo_transform.md)
- [Evolve](demo_evolve.md)
MD
